apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-pvc
  labels:
    app: ha
    data: config
spec:
  storageClassName: vc01cl01-t0compute
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
