version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/vmware/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      #- /dev/ttyUSB0:/dev/ttyUSB0 #External devices
    restart: unless-stopped
    privileged: true
    
    network_mode: host
    #ports:
    #  - 8123:8123