apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ha-pvc
        - name: homeassist-config
          secret:
            secretName: homeassist-config
            defaultMode: 0777
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:stable
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/config/configuration.yaml"
              subPath: "configuration.yaml"
              name: homeassist-config
